### ISSUE TITLE
Question about static libraries

### ISSUE THREAD

**Issue by ellipse12** [c3lang/vendor#23]
@lerno Should I include the compiled library for every version in this repo or should I just include the bindings and manifest.json?

**Comment by lerno** [comment]
If the compiled, static library is available then it's a nice service to include it. Otherwise don't

**Comment by ellipse12** [comment]
ok, that would likely mean that only a subset of architectures/targets would be included is that alright?

**Comment by lerno** [comment]
Some architectures/targets can have the lib missing (see curl) as it's then assumed the user then uses a dylib.

**Comment by ellipse12** [comment]
ok thank you
