### ISSUE TITLE
WebGPU

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [c3lang/vendor#26]
In case you're interested, I made WebGPU bindings for my own use:
https://github.com/TheOnlySilverClaw/webgpu.c3l

Any interest in including these?

**Comment by lerno** [comment]
Absolutely!

**Comment by TheOnlySilverClaw** [comment]
Any policy on how to handle the binary dependencies? There's two possible implementations (wgpu-native and Dawn) and both are pretty big binaries one would have to link. And both are basically optional when building for a browser target.

**Comment by lerno** [comment]
Either place the actual binaries in there, otherwise just add the linker arguments and add a note about the need to supply the library.

**Comment by lerno** [comment]
Added, so I close this one.
