### ISSUE TITLE
`raylib5.c3l` failing to link with `glfw3`

### ISSUE THREAD

**Issue by Book-reader** [c3lang/vendor#29]
on arch, fedora, and debian linux, `glfw3` is linked with using `-lglfw` instead of `-lglfw3`.
this causes `raylib5.c3l` and `raylib.c3l` to fail to build with the message `/usr/bin/ld: cannot find -lglfw3: No such file or directory`.
it can be fixed by replacing `"linked-libraries" : [ "glfw3" ]` with `"linked-libraries" : [ "glfw" ]`

**Comment by lerno** [comment]
Ok, from what I see on the Raylib site, glfw3 is the correct one. Unless glfw works on ALL Linux distros, some other solution must be found.

**Comment by Book-reader** [comment]
after more testing,
method: install gcc and `glfw3` (`libglfw3-dev`, `glfw-devel`, etc) in a distrobox container, then run a raylib hello world that uses the library, but use either `glfw` or `glfw3` in the `manifest.json` of `raylib5.c3l`
work means the program ran
fail means the compilation failed with the error `/usr/bin/ld: cannot find -lglfw3: No such file or directory`
|Distro | glfw      | glfw3      |
|---------------| ------------- | ------------- |
|Arch| work | fail |
|Fedora 40| work | fail |
|Debian 12| work | fail |
|Ubuntu 24.04| work | fail |
|OpenSUSE Tumbleweed| work | fail |

also `glfw.c3l` uses `"linked-libraries" : [ "glfw" ]`

running `pkg-config --libs glfw3` also returns `-lglfw`

**Comment by Book-reader** [comment]
To clarify my incoherent ramblings, I belive that -lglfw is the correct way to link with glfw3, when installed using a system package manager as can be seen in the raylib makefile:
```
# Check the version name. If GLFW3 was built manually, it may have produced
# a static library known as libglfw3.a. In that case, the name should be -lglfw3
LDLIBS = -lglfw
```
