### ISSUE TITLE
Wrong Windows Vulkan lib name

### ISSUE THREAD

**Issue by kulkalkul** [c3lang/vendor#31]
https://github.com/c3lang/vendor/blob/main/libraries/vulkan.c3l/manifest.json#L114

This results for vulkan.lib lookup, but it should be vulkan-1.lib for Windows (that's the name in VulkanSDK\1.3.296.0\Lib)

![image](https://github.com/user-attachments/assets/e4afe0e8-75f3-44e8-ac5f-79081d92d197)

**Comment by lerno** [comment]
I'll accept a pull request for it! :D

**Comment by kulkalkul** [comment]
Fixed with: #32
